"""보고서 HTML 내보내기 — 새 sections 기반 구조."""

from reports.generator import get_branch_report


def render_html_report(branch_id: int, year: int = None, month: int = None) -> str:
    """지점별 보고서를 HTML로 렌더링."""
    data = get_branch_report(branch_id, year, month)
    if not data:
        return "<html><body><h1>지점을 찾을 수 없습니다</h1></body></html>"

    period_text = f"{year}년 {month}월" if year and month else "전체"

    html = f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{data['branch_name']} — 마케팅 보고서</title>
<style>
  * {{ margin: 0; padding: 0; box-sizing: border-box; }}
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #334155; line-height: 1.6; padding: 40px; max-width: 800px; margin: 0 auto; }}
  h1 {{ font-size: 24px; margin-bottom: 4px; color: #1e293b; }}
  h2 {{ font-size: 18px; margin: 32px 0 12px; color: #475569; border-bottom: 2px solid #e2e8f0; padding-bottom: 6px; }}
  .subtitle {{ font-size: 14px; color: #94a3b8; margin-bottom: 32px; }}
  .card {{ background: #f8fafc; border-radius: 8px; padding: 16px; margin-bottom: 12px; }}
  .stat {{ display: inline-block; margin-right: 24px; }}
  .stat-value {{ font-size: 24px; font-weight: 700; color: #3b82f6; }}
  .stat-label {{ font-size: 12px; color: #94a3b8; }}
  .post {{ padding: 6px 0; border-bottom: 1px solid #f1f5f9; font-size: 13px; }}
  .post a {{ color: #3b82f6; text-decoration: none; }}
  .post a:hover {{ text-decoration: underline; }}
  .print-btn {{ position: fixed; top: 20px; right: 20px; padding: 8px 16px; background: #3b82f6; color: white; border: none; border-radius: 8px; cursor: pointer; font-size: 13px; }}
  @media print {{ .print-btn {{ display: none; }} }}
</style>
</head>
<body>
<button class="print-btn" onclick="window.print()">PDF 다운로드</button>
<h1>{data['branch_name']}</h1>
<p class="subtitle">마케팅 보고서 | {period_text}</p>
"""

    for section in data.get("sections", []):
        key = section["key"]
        title = section["title"]
        d = section["data"]

        html += f'<h2>{title}</h2>'

        if key in ("brand_blog", "opt_blog"):
            html += f'<div class="card"><div class="stat"><span class="stat-value">{d["total"]}</span><br><span class="stat-label">게시글</span></div></div>'
            for p in d.get("posts", [])[:15]:
                url = p.get("published_url", "")
                title_text = p.get("title") or "(제목 없음)"
                link = f'<a href="{url}" target="_blank">링크</a>' if url else ""
                html += f'<div class="post">{link} {title_text}</div>'

        elif key == "cafe":
            html += f'<div class="card"><div class="stat"><span class="stat-value">{d["total"]}</span><br><span class="stat-label">원고</span></div></div>'
            for a in d.get("articles", [])[:10]:
                html += f'<div class="post">{a.get("title", "(제목 없음)")} <span style="color:#94a3b8">{a.get("status", "")}</span></div>'

        elif key == "place":
            html += f"""<div class="card">
  <div class="stat"><span class="stat-value">{d['exposed_days']}</span><br><span class="stat-label">노출일</span></div>
  <div class="stat"><span class="stat-value">{d['exposure_rate']}%</span><br><span class="stat-label">노출률</span></div>
</div>"""

        elif key == "webpage":
            html += f"""<div class="card">
  <div class="stat"><span class="stat-value">{d['exposed_days']}</span><br><span class="stat-label">노출일</span></div>
  <div class="stat"><span class="stat-value">{d['exposure_rate']}%</span><br><span class="stat-label">노출률</span></div>
</div>"""

        elif key == "complaints":
            sc = d.get("status_counts", {})
            html += f"""<div class="card">
  <div class="stat"><span class="stat-value">{d['total']}</span><br><span class="stat-label">총 민원</span></div>
  <div class="stat"><span class="stat-value">{sc.get('received', 0) + sc.get('processing', 0)}</span><br><span class="stat-label">처리 대기</span></div>
  <div class="stat"><span class="stat-value">{sc.get('resolved', 0) + sc.get('closed', 0)}</span><br><span class="stat-label">처리 완료</span></div>
</div>"""

    if not data.get("sections"):
        html += '<p style="text-align:center; color:#94a3b8; padding:40px 0;">해당 기간에 진행된 마케팅 내역이 없습니다.</p>'

    html += """
<p style="margin-top: 48px; text-align: center; font-size: 12px; color: #94a3b8;">
  Generated by 유앤아이의원 통합 관리 시스템
</p>
</body></html>"""

    return html
